# ------------------------------------------------------------------------------
# VLLM Simulator
#
# This deploys a VLLM simulator which can be used to simulate inference for
# small environments (e.g. Kubernetes In Docker (KIND) clusters), or for when
# all that is needed is some basic functionality.
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployments.yaml

images:
- name: ghcr.io/llm-d/llm-d-inference-sim
  newTag: ${VLLM_SIMULATOR_TAG}
- name: ghcr.io/llm-d/llm-d-routing-sidecar
  newTag: ${ROUTING_SIDECAR_TAG}
